[package]
name = "parser"
version = "0.1.0"
authors = ["Adrian Neumann <adrian_neumann@gmx.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
rand = "0.7"

